import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";
import { init } from "@/lib/onload";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Login to Gerald AI™",
  description:
    "Generated by your cousins nephew. He's a nefarious little bastard most of the time but he his pretty tech-savvy."
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
      <Script id="onload-script">
        {`window.onload = () => (${init.toString()})()`}
      </Script>
    </html>
  );
}
