import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "@/providers";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900"
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900"
});
const apfelGrotezk = localFont({
  src: "./fonts/ApfelGrotezk-Regular.woff",
  variable: "--font-apfel-grotezk",
  weight: "100 900"
});

export const metadata: Metadata = {
  title: "Login to Gerald AI™",
  description:
    "Generated by your cousins nephew. He's a nefarious little bastard most of the time but he his pretty tech-savvy."
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${apfelGrotezk.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
